### PR TITLE
Feature/stats reminder

### PR DESCRIPTION
**Pull request by Braun-Johannes**
In this PR we also removed some console warnings by adding a "$" to props.

Also we removed a small bug from selecting the first pet with empty localstorage.

### CODE REVIEW

**Review by evabergold — CHANGES_REQUESTED** [review]
Your code looks good to me, however I found some behaviour which I think is not intended (maybe this is already more QA, but as I found it I thought I'd mention it): If I actively eliminate a pet, all snackbars are shown at the same time for a few seconds. Same when my pet dies, I close the browser and open it again. 

As this does not happen when I keep the app open and watch the stats decrease and the pet finally dies, maybe you want to have another look at this :-)

**Comment by ChristianMoschke** [comment]
In `index.js` you have a `StyledLink` component. You set `align-items` to `flex` which doesn't work, since this isn't a valid property.
Check this for reference: https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

**Comment by ChristianMoschke** [comment]
In `SVGIcon.jsx` you have an unused parameter `text` in line 8.

**Review by ChristianMoschke — APPROVED** [review]
I found a few things. Address them, and you’ll be ready for QA!

**Pull request merged**
